### ISSUE TITLE
[Bug]: Defense buff not working

### ISSUE THREAD

**Issue by silverforte** [promcteam/proskillapi#153]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I applied DEFENSE to a buff, tested it thoroughly both with and without armor. no change between pre-buff and post-buff. seems to have no effect with mobs. neither does armor stat.

### Expected Behavior

should give defense buff

### Environment

```markdown
- Server Software:
- ProSkillAPI Version:
- ProMCCore Version:
- Plugins:
```

### latest.log

[18:34:02] [Server thread/ERROR]: Failed to cast skill - Repulse: Internal skill error
[18:34:02] [Server thread/WARN]: java.lang.IllegalArgumentException: No enum constant com.sucy.skill.api.enums.Operation.operation
[18:34:02] [Server thread/WARN]:        at java.base/java.lang.Enum.valueOf(Enum.java:273)
[18:34:02] [Server thread/WARN]:        at com.sucy.skill.api.enums.Operation.valueOf(Operation.java:6)
[18:34:02] [Server thread/WARN]:        at com.sucy.skill.dynamic.mechanic.StatMechanic.execute(StatMechanic.java:83)
[18:34:02] [Server thread/WARN]:        at com.sucy.skill.dynamic.EffectComponent.executeChildren(EffectComponent.java:242)
[18:34:02] [Server thread/WARN]:        at com.sucy.skill.dynamic.target.TargetComponent.execute(TargetComponent.java:54)
[18:34:02] [Server thread/WARN]:        at com.sucy.skill.dynamic.EffectComponent.executeChildren(EffectComponent.java:242)
[18:34:02] [Server thread/WARN]:        at com.sucy.skill.dynamic.trigger.TriggerComponent.execute(TriggerComponent.java:44)
[18:34:02] [Server thread/WARN]:        at com.sucy.skill.dynamic.trigger.TriggerComponent.trigger(TriggerComponent.java:27)
[18:34:02] [Server thread/WARN]:        at com.sucy.skill.dynamic.DynamicSkill.trigger(DynamicSkill.java:353)
[18:34:02] [Server thread/WARN]:        at com.sucy.skill.dynamic.DynamicSkill.cast(DynamicSkill.java:259)
[18:34:02] [Server thread/WARN]:        at com.sucy.skill.dynamic.DynamicSkill.cast(DynamicSkill.java:264)
[18:34:02] [Server thread/WARN]:        at com.sucy.skill.api.player.PlayerData.cast(PlayerData.java:2064)
[18:34:02] [Server thread/WARN]:        at com.sucy.skill.listener.BindListener.onInteract(BindListener.java:71)
[18:34:02] [Server thread/WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:34:02] [Server thread/WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[18:34:02] [Server thread/WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:34:02] [Server thread/WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[18:34:02] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[18:34:02] [Server thread/WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[18:34:02] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
[18:34:02] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
[18:34:02] [Server thread/WARN]:        at com.sucy.skill.packet.PacketHandler.lambda$callEvent$0(PacketHandler.java:55)
[18:34:02] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:82)
[18:34:02] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415)
[18:34:02] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1269)
[18:34:02] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:438)
[18:34:02] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1217)
[18:34:02] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1050)
[18:34:02] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305)
[18:34:02] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by goflishMC** [comment]
You need to fill this out 

- Server Software:
- ProSkillAPI Version:
- ProMCCore Version:
- Plugins:

Also, can you drop your skill file in here too?

**Comment by Travja** [comment]
StatMechanic was broken by some code being unintentionally left behind. This has been fixed and will be coming soon with the new build.
