### ISSUE TITLE
[Bug]: attribute Mechanic  still broken in Proskillapi 1.1.7.6

### ISSUE THREAD

**Issue by mcps901313** [promcteam/proskillapi#156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

attribute Mechanic  still broken in Proskillapi 1.1.7.6

### Environment

```markdown
- Server Software: paper 1.16.5
- ProSkillAPI Version: Proskillapi 1.1.7.6
- ProMCCore Version:  1.0.3.2-ALPHA
- Plugins:
```

### latest.log

[15:21:12 WARN]: [ProSkillAPI] Task #54871 for ProSkillAPI v1.1.7.6-ALPHA generated an exception
java.lang.IllegalArgumentException: No enum constant com.sucy.skill.api.enums.Operation.operation
        at java.lang.Enum.valueOf(Unknown Source) ~[?:1.8.0_301]
        at com.sucy.skill.api.enums.Operation.valueOf(Operation.java:6) ~[?:?]
        at com.sucy.skill.dynamic.mechanic.AttributeMechanic.execute(AttributeMechanic.java:83) ~[?:?]
        at com.sucy.skill.dynamic.EffectComponent.executeChildren(EffectComponent.java:242) ~[?:?]
        at com.sucy.skill.dynamic.mechanic.PassiveMechanic.access$500(PassiveMechanic.java:43) ~[?:?]
        at com.sucy.skill.dynamic.mechanic.PassiveMechanic$PassiveTask.run(PassiveMechanic.java:124) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-788]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:485) ~[patched_1.16.5.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1427) ~[patched_1.16.5.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342) ~[patched_1.16.5.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-788]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_301]

### Anything else?

_No respons
[test.txt](https://github.com/promcteam/proskillapi/files/7586366/test.txt)
e_

**Comment by goflishMC** [comment]
stop your server, delete your attributes.yml and then start your server back up and let it regenerate.

Nobody else has reported attributes not working. They work fine for me.

**Comment by EyatMC** [comment]
Please use pastebin.

**Comment by Travja** [comment]
The error that is being thrown is not consistent with the latest code. If you do indeed have just 1.1.7.6 loaded up, it appears that it might not have compiled correctly or goflish accidentally posted the wrong build. Just to confirm, you got the build as it was posted on Github, correct?

**Comment by mcps901313** [comment]
yes
https://github.com/promcteam/proskillapi/releases
On github download

ProSkillAPI-1.1.7.6-ALPHA.jar
ProMCCore-1.0.3.2-ALPHA

**Comment by Travja** [comment]
I've updated that release with the proper jar. Please redownload it and try again.
