### ISSUE TITLE
[Bug]: Class skill bug

### ISSUE THREAD

**Issue by novaechiro** [promcteam/proskillapi#202]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Skill is not showing up when skill tree type is Requirement, and other type got errors in the latest log below

### Expected Behavior

Got the "Farming" skill in the skill tree

### Environment

```markdown
- Server Software: Spigot 1.17.1
- ProSkillAPI Version:1.1.7.12
- ProMCCore Version:1.0.3.5
- Plugins: Proskillapi
```

### latest.log

[09:02:51] [Server thread/INFO]: Novaechiro issued server command: /class skill
[09:02:51] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'class skill' in class
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:156) ~[spigot.jar:3284a-Spigot-3892929-0ab8487]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:790) ~[spigot.jar:3284a-Spigot-3892929-0ab8487]
	at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:1931) ~[spigot.jar:3284a-Spigot-3892929-0ab8487]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1770) ~[spigot.jar:3284a-Spigot-3892929-0ab8487]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1751) ~[spigot.jar:3284a-Spigot-3892929-0ab8487]
	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46) ~[spigot.jar:3284a-Spigot-3892929-0ab8487]
	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot.jar:3284a-Spigot-3892929-0ab8487]
	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) ~[spigot.jar:3284a-Spigot-3892929-0ab8487]
	at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot.jar:3284a-Spigot-3892929-0ab8487]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151) ~[spigot.jar:3284a-Spigot-3892929-0ab8487]
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot.jar:3284a-Spigot-3892929-0ab8487]
	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125) ~[spigot.jar:3284a-Spigot-3892929-0ab8487]
	at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1148) ~[spigot.jar:3284a-Spigot-3892929-0ab8487]
	at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1141) ~[spigot.jar:3284a-Spigot-3892929-0ab8487]
	at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(SourceFile:134) ~[spigot.jar:3284a-Spigot-3892929-0ab8487]
	at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1125) ~[spigot.jar:3284a-Spigot-3892929-0ab8487]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1054) ~[spigot.jar:3284a-Spigot-3892929-0ab8487]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) ~[spigot.jar:3284a-Spigot-3892929-0ab8487]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalArgumentException: Size for custom inventory must be a multiple of 9 between 9 and 54 slots (got 0)
	at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[spigot.jar:3284a-Spigot-3892929-0ab8487]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.createInventory(CraftServer.java:1843) ~[spigot.jar:3284a-Spigot-3892929-0ab8487]
	at com.sucy.skill.gui.tool.GUIData.show(GUIData.java:75) ~[?:?]
	at com.sucy.skill.api.player.PlayerData.showSkills(PlayerData.java:1078) ~[?:?]
	at com.sucy.skill.api.player.PlayerData.showSkills(PlayerData.java:1053) ~[?:?]
	at com.sucy.skill.cmd.CmdSkill.execute(CmdSkill.java:67) ~[?:?]
	at mc.promcteam.engine.mccore.commands.ConfigurableCommand.execute(ConfigurableCommand.java:514) ~[?:?]
	at mc.promcteam.engine.mccore.commands.ConfigurableCommand.execute(ConfigurableCommand.java:521) ~[?:?]
	at mc.promcteam.engine.mccore.commands.ConfigurableCommand.execute(ConfigurableCommand.java:484) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot.jar:3284a-Spigot-3892929-0ab8487]
	... 18 more

### Anything else?

[latest.log](https://github.com/promcteam/proskillapi/files/7804981/latest.log)

**Comment by Travja** [comment]
@novaechiro The error you're getting here looks like it should be related to inventory sizes not anything to do with the skills themselves. Could you try with some new test skills/classes and make sure that this is an issue when building your guis from the ground up?
