### ISSUE TITLE
[Bug]: Problem with /class customize

### ISSUE THREAD

**Issue by luoxiawuchen** [promcteam/proskillapi#232]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Steps To Reproduce

1、Enter the command /class customize
2、click “next menu”
![image](https://user-images.githubusercontent.com/64759847/153192220-e7a92ae4-b8e3-4878-82e0-549fe7377760.png)
3、In the class details interface and attributes interface, you need to click twice to switch to the next page, and an error will be thrown
-----------------------------------------------------------------
[19:37:19 ERROR]: Could not pass event InventoryClickEvent to ProSkillAPI v1.1.7.14-ALPHA
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
        at com.sucy.skill.gui.tool.GUITool.getActiveData(GUITool.java:232) ~[?:?]
        at com.sucy.skill.gui.tool.GUITool.setType(GUITool.java:289) ~[?:?]
        at com.sucy.skill.gui.tool.GUITool.handleClick(GUITool.java:502) ~[?:?]
        at com.sucy.skill.listener.ToolListener.onClick(ToolListener.java:48) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor65.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-794]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2715) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1271) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1264) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1225) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1139) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:831) [?:?]

### Environment

```markdown
- Server Software: Paper Spigot 1.16.5
- ProSkillAPI Version: 1.1.7.14-ALPHA
- ProMCCore Version: 1.0.3.6-ALPHA
- Plugins: promccore-1.0.3.6-ALPHA、proskillapi-1.1.7.14-ALPHA、ProSkillAPIParties-1.0-snapshot
```

**Comment by Travja** [comment]
I'm going to close this as I haven't experienced this issue. If you're still having problems, I would just recommend regenerating your configs (obviously backing up your skills/classes). This usually happens when a config file gets improperly saved or configured.
