### ISSUE TITLE
[Bug] Drop, offhand action of Click Combos not working and more

### ISSUE THREAD

**Issue by TNG-China** [promcteam/proskillapi#24]
Drop action just not working and the offhand action throw an error about string of the skill when casting:
`Caused by: java.lang.NullPointerException
	at com.sucy.skill.data.Click.getName(Click.java:86) ~[?:?]
	at com.sucy.skill.manager.ComboManager.getComboString(ComboManager.java:256) ~[?:?]
	at com.sucy.skill.manager.ComboManager.getComboString(ComboManager.java:236) ~[?:?]
	at com.sucy.skill.api.player.PlayerCombos.getComboString(PlayerCombos.java:331) ~[?:?]
	at com.sucy.skill.api.skills.Skill.getIndicator(Skill.java:641) ~[?:?]
	at com.sucy.skill.api.skills.Skill.getIcon(Skill.java:486) ~[?:?]
	at com.sucy.skill.gui.tool.GUIPage.instance(GUIPage.java:154) ~[?:?]
	at com.sucy.skill.gui.tool.GUIData.show(GUIData.java:82) ~[?:?]
	at com.sucy.skill.api.player.PlayerData.showSkills(PlayerData.java:959) ~[?:?]
	at com.sucy.skill.api.player.PlayerData.showSkills(PlayerData.java:940) ~[?:?]
	at com.sucy.skill.cmd.CmdSkill.execute(CmdSkill.java:75) ~[?:?]
	at com.rit.sucy.commands.ConfigurableCommand.execute(ConfigurableCommand.java:550) ~[?:?]
	at com.rit.sucy.commands.ConfigurableCommand.execute(ConfigurableCommand.java:558) ~[?:?]
	at com.rit.sucy.commands.ConfigurableCommand.execute(ConfigurableCommand.java:516) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-756]
	... 18 more`

Space action even triggers when you go up the stairs.

**Comment by goflishMC** [comment]
We need a copy of your entire startup log.

Also, you need to explain to us how to make that error happen
