### ISSUE TITLE
[Bug]: "class acc" command doesnt work neither does the "class switch" when enabling it

### ISSUE THREAD

**Issue by Colderjacket** [promcteam/proskillapi#255]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

In the config.yml one can change the attribute "one-per-class: " key either to "true" or "false".
But the class switch command, if one enables the one per class key, provides an error as pasted down below.

When disabling that system one can use the class account system. But if i type for example:
/class acc 3 it says:
"That is not a valid account Id".
But that happens regardless what number i type after the "/class acc".

### Expected Behavior

Class Account System
Normally one can switch between the accounts to play with different builds.

Class Switch System
Normally there is automatically a class account provided for each class, but using that command straight up throws an error.

### Steps To Reproduce

As mentioned above, trying typing class account will not switch the account.
/class switch throws an error.

### Environment

```markdown
- Server Software: Purpur Spigot 1.18.1-1496
- ProSkillAPI Version: 1.1.7.14-ALPHA
- ProMCCore Version: 1.0.3.6-ALPHA
- Plugins: ProSkillAPI, ProMCCore
```

### latest.log

Upon Switching class with /class switch command

[16:25:41] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'class switch Rogue' in class
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:182) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:897) ~[purpur-1.18.1.jar:git-Purpur-1496]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2368) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2179) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2160) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.1.jar:git-Purpur-1496]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1440) ~[purpur-1.18.1.jar:git-Purpur-1496]
	at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[purpur-1.18.1.jar:git-Purpur-1496]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1418) ~[purpur-1.18.1.jar:git-Purpur-1496]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1411) ~[purpur-1.18.1.jar:git-Purpur-1496]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1389) ~[purpur-1.18.1.jar:git-Purpur-1496]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1295) ~[purpur-1.18.1.jar:git-Purpur-1496]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.1.jar:git-Purpur-1496]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.scoreboard.Scoreboard.resetScores(String)" because "mc.promcteam.engine.mccore.scoreboard.BoardManager.scoreboard" is null
	at mc.promcteam.engine.mccore.scoreboard.BoardManager.clearScore(BoardManager.java:182) ~[promccore-1.0.3.6-ALPHA.jar:?]
	at com.sucy.skill.manager.ClassBoardManager.clear(ClassBoardManager.java:56) ~[proskillapi-1.1.7.14-ALPHA.jar:?]
	at com.sucy.skill.api.player.PlayerAccounts.setAccount(PlayerAccounts.java:206) ~[proskillapi-1.1.7.14-ALPHA.jar:?]
	at com.sucy.skill.api.player.PlayerAccounts.setAccount(PlayerAccounts.java:178) ~[proskillapi-1.1.7.14-ALPHA.jar:?]
	at com.sucy.skill.cmd.CmdSwitch.execute(CmdSwitch.java:100) ~[proskillapi-1.1.7.14-ALPHA.jar:?]
	at mc.promcteam.engine.mccore.commands.ConfigurableCommand.execute(ConfigurableCommand.java:514) ~[promccore-1.0.3.6-ALPHA.jar:?]
	at mc.promcteam.engine.mccore.commands.ConfigurableCommand.execute(ConfigurableCommand.java:521) ~[promccore-1.0.3.6-ALPHA.jar:?]
	at mc.promcteam.engine.mccore.commands.ConfigurableCommand.execute(ConfigurableCommand.java:484) ~[promccore-1.0.3.6-ALPHA.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	... 20 more

**Comment by Travja** [comment]
This should be resolved in upcoming versions. If you're still having issues, it could be a conflicting scoreboard plugin.
