### ISSUE TITLE
[Bug]: config won't build up and won't load plugin 

### ISSUE THREAD

**Issue by tomokopter2137** [promcteam/proskillapi#275]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

dunno why im tryin to load this plugin but the config is not loading in files and when i try to start server thats what is showing up:
java.lang.NoClassDefFoundError: mc/promcteam/engine/utils/reflection/ReflectionUtil
        at com.sucy.skill.api.particle.Particle.init(Particle.java:76) ~[?:?]
        at com.sucy.skill.SkillAPI.onEnable(SkillAPI.java:609) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:517) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3470-Spigot-ffceeae-1092219]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:431) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3470-Spigot-ffceeae-1092219]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:612) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3470-Spigot-ffceeae-1092219]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3470-Spigot-ffceeae-1092219]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:263) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3470-Spigot-ffceeae-1092219]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1007) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3470-Spigot-ffceeae-1092219]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3470-Spigot-ffceeae-1092219]
        at java.lang.Thread.run(Thread.java:833) [?:?]

### Expected Behavior

load a plugin

### Environment

```markdown
- Server Software:
- ProSkillAPI Version:
- ProMCCore Version:
- Plugins:
```

**Comment by Sentropic** [comment]
You have to use the latest versions of ProSkillAPI and ProMCCore (currently only published in #announcements in the discord server)

**Comment by Sentropic** [comment]
Oh sorry! I just updated the link here on GitHub, it should work now

**Comment by Sentropic** [comment]
Let me know if that's fixes the issue, so we can close it

**Comment by tomokopter2137** [comment]
i have to wait till tomorrow evening to try it, you can close it and if it wont help, i will text ya on discord if its not a problem

**Comment by Sentropic** [comment]
Did it work?
