### ISSUE TITLE
[Bug]: Taunt on Mythicmobs Without Threat Table

### ISSUE THREAD

**Issue by lordsrubka5** [promcteam/proskillapi#299]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

If a Mythicmob in range does not have threat table turned on, Taunt mechanic
will provide an error and the casting of that skill will fail casting mid way without
triggering some mechanics, cooldown and mana.

### Expected Behavior

This can be easily avoided by just adding threat table to all mobs but its something to note

### Environment

```markdown
-
```

### latest.log

[22:57:08 ERROR]: [ProSkillAPI] Failed to cast skill - PaladinTaunt: Internal skill error
[22:57:08 WARN]: java.lang.NullPointerException: Cannot invoke "io.lumine.mythic.core.mobs.ActiveMob$ThreatTable.threatGain(io.lumine.mythic.api.adapters.AbstractEntity, double)" because the return value of "io.lumine.mythic.core.mobs.ActiveMob.getThreatTable()" is null
[22:57:08 WARN]:        at promccore-1.0.3.9-1910433.jar//mc.promcteam.engine.hooks.external.MythicMobsHKv5.taunt(MythicMobsHKv5.java:140)
[22:57:08 WARN]:        at proskillapi-1.1.7.17-1712011.jar//com.sucy.skill.hook.MythicMobsHook.taunt(MythicMobsHook.java:13)
[22:57:08 WARN]:        at proskillapi-1.1.7.17-1712011.jar//com.sucy.skill.dynamic.mechanic.TauntMechanic.execute(TauntMechanic.java:68)
[22:57:08 WARN]:        at proskillapi-1.1.7.17-1712011.jar//com.sucy.skill.dynamic.EffectComponent.executeChildren(EffectComponent.java:229)
[22:57:08 WARN]:        at proskillapi-1.1.7.17-1712011.jar//com.sucy.skill.dynamic.condition.SkillLevelCondition.execute(SkillLevelCondition.java:46)
[22:57:08 WARN]:        at proskillapi-1.1.7.17-1712011.jar//com.sucy.skill.dynamic.EffectComponent.executeChildren(EffectComponent.java:229)
[22:57:08 WARN]:        at proskillapi-1.1.7.17-1712011.jar//com.sucy.skill.dynamic.target.TargetComponent.execute(TargetComponent.java:58)
[22:57:08 WARN]:        at proskillapi-1.1.7.17-1712011.jar//com.sucy.skill.dynamic.EffectComponent.executeChildren(EffectComponent.java:229)
[22:57:08 WARN]:        at proskillapi-1.1.7.17-1712011.jar//com.sucy.skill.dynamic.trigger.TriggerComponent.execute(TriggerComponent.java:44)
[22:57:08 WARN]:        at proskillapi-1.1.7.17-1712011.jar//com.sucy.skill.dynamic.trigger.TriggerComponent.trigger(TriggerComponent.java:27)
[22:57:08 WARN]:        at proskillapi-1.1.7.17-1712011.jar//com.sucy.skill.dynamic.DynamicSkill.trigger(DynamicSkill.java:341)
[22:57:08 WARN]:        at proskillapi-1.1.7.17-1712011.jar//com.sucy.skill.dynamic.DynamicSkill.cast(DynamicSkill.java:259)
[22:57:08 WARN]:        at proskillapi-1.1.7.17-1712011.jar//com.sucy.skill.dynamic.DynamicSkill.cast(DynamicSkill.java:264)
[22:57:08 WARN]:        at proskillapi-1.1.7.17-1712011.jar//com.sucy.skill.api.player.PlayerData.cast(PlayerData.java:2101)
[22:57:08 WARN]:        at proskillapi-1.1.7.17-1712011.jar//com.sucy.skill.api.player.PlayerData.cast(PlayerData.java:2058)
[22:57:08 WARN]:        at proskillapi-1.1.7.17-1712011.jar//com.sucy.skill.api.player.PlayerCombos.applyClick(PlayerCombos.java:138)
[22:57:08 WARN]:        at proskillapi-1.1.7.17-1712011.jar//com.sucy.skill.listener.ComboListener.onClick(ComboListener.java:90)
[22:57:08 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor653.execute(Unknown Source)
[22:57:08 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[22:57:08 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[22:57:08 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[22:57:08 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[22:57:08 WARN]:        at proskillapi-1.1.7.17-1712011.jar//com.sucy.skill.listener.ClickListener.onClick(ClickListener.java:59)
[22:57:08 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor650.execute(Unknown Source)
[22:57:08 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[22:57:08 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[22:57:08 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[22:57:08 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[22:57:08 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:543)
[22:57:08 WARN]:        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:544)
[22:57:08 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1887)
[22:57:08 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:33)
[22:57:08 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:9)
[22:57:08 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[22:57:08 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[22:57:08 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[22:57:08 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[22:57:08 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1450)
[22:57:08 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192)
[22:57:08 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[22:57:08 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1428)
[22:57:08 WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1421)
[22:57:08 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[22:57:08 WARN]:        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1399)
[22:57:08 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1310)
[22:57:08 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322)
[22:57:08 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by Travja** [comment]
So I can address this by simply checking if the threat table exists, if not, do nothing. Is that acceptable? Or should some other result be preferred if no threat table exists?

**Comment by lordsrubka5** [comment]
Not sure how much can be done with normal mob targeting AI.
Quickest fix right now would be just making it do nothing if table is null.

Later it can be made so that positive forces the mob to target the caster and negative to force
the mob to target another player IF the caster was targeted by the mob at the point of casting
But that part becomes more of a suggestion than a bug report so it doesn't need to be implemented
that fast as no one else is complaining and I just enabled threat tables.

**Comment by Travja** [comment]
I can totally force the mob to target the player on a positive value. Negative gets a little harder because I can cause the mob not to target the player, but forcing it to target another becomes a logistical problem since I'm not sure how MythicMobs would handle that.

This is the potential code that I have in place right now, which I'll go ahead and publish here in a minute if you'd like to try it out.
```java
    public void taunt(LivingEntity target, LivingEntity source, double amount) {
        AbstractEntity abs = BukkitAdapter.adapt(source);
        ActiveMob      mob = getActiveMythicInstance(target);
        if (!mob.hasThreatTable()) {
            if (amount > 0) mob.setTarget(abs); // Here we're setting the mob's target to the caster
            else if (amount < 0) mob.getNewTarget(); // If the amount is negative, get a new target?
            return;
        }

        ActiveMob.ThreatTable table = mob.getThreatTable();
        if (amount > 0) table.threatGain(abs, amount);
        else if (amount < 0) table.threatLoss(abs, -amount);
    }
```
