### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Avaely** [promcteam/proskillapi#340]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

I have no idea but im guessing it's clientside, i've already redone the skill and class 2 - 3 times since it's my first time using it in the editor, i thought it was due to me doing something wrong but i checked logs and i saw this

<html>
<body>

[15:15:12] [Server thread/INFO]: MatsuroCh issued server command: /class reload
--
593 | [15:15:12] [Server thread/ERROR]: [ProSkillAPI] Failed to load skill: HumanSkillAirSlash - Cannot invoke "mc.promcteam.engine.mccore.config.parse.DataSection.getString(String, String)" because "config" is null
594 | [15:15:12] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "mc.promcteam.engine.mccore.config.parse.DataSection.getString(String, String)" because "config" is null
595 | [15:15:12] [Server thread/WARN]: 	at com.sucy.skill.api.skills.Skill.load(Skill.java:852)
596 | [15:15:12] [Server thread/WARN]: 	at com.sucy.skill.dynamic.DynamicSkill.load(DynamicSkill.java:351)
597 | [15:15:12] [Server thread/WARN]: 	at com.sucy.skill.manager.RegistrationManager.lambda$initialize$0(RegistrationManager.java:181)
598 | [15:15:12] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
599 | [15:15:12] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
600 | [15:15:12] [Server thread/WARN]: 	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
601 | [15:15:12] [Server thread/WARN]: 	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
602 | [15:15:12] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
603 | [15:15:12] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
604 | [15:15:12] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
605 | [15:15:12] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
606 | [15:15:12] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
607 | [15:15:12] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
608 | [15:15:12] [Server thread/WARN]: 	at com.sucy.skill.manager.RegistrationManager.initialize(RegistrationManager.java:170)
609 | [15:15:12] [Server thread/WARN]: 	at com.sucy.skill.SkillAPI.onEnable(SkillAPI.java:639)
610 | [15:15:12] [Server thread/WARN]: 	at com.sucy.skill.SkillAPI.reload(SkillAPI.java:534)
611 | [15:15:12] [Server thread/WARN]: 	at com.sucy.skill.cmd.CmdReload.execute(CmdReload.java:53)
612 | [15:15:12] [Server thread/WARN]: 	at mc.promcteam.engine.mccore.commands.ConfigurableCommand.execute(ConfigurableCommand.java:514)
613 | [15:15:12] [Server thread/WARN]: 	at mc.promcteam.engine.mccore.commands.ConfigurableCommand.execute(ConfigurableCommand.java:521)
614 | [15:15:12] [Server thread/WARN]: 	at mc.promcteam.engine.mccore.commands.ConfigurableCommand.execute(ConfigurableCommand.java:484)
615 | [15:15:12] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
616 | [15:15:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826)
617 | [15:15:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2185)
618 | [15:15:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2000)
619 | [15:15:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1953)
620 | [15:15:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49)
621 | [15:15:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7)
622 | [15:15:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35)
623 | [15:15:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
624 | [15:15:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
625 | [15:15:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
626 | [15:15:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
627 | [15:15:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1271)
628 | [15:15:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1264)
629 | [15:15:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
630 | [15:15:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1225)
631 | [15:15:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1139)
632 | [15:15:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
633 | [15:15:12] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
634 | [15:15:12] [Server thread/INFO]: [ProSkillAPI] Registration complete
635 | [15:15:12] [Server thread/INFO]: [ProSkillAPI]  - 0 skills
636 | [15:15:12] [Server thread/INFO]: [ProSkillAPI]  - 1 classes

</body>
</html>[15:15:12] [Server thread/INFO]: MatsuroCh issued server command: /class reload
[15:15:12] [Server thread/ERROR]: [ProSkillAPI] Failed to load skill: HumanSkillAirSlash - Cannot invoke "mc.promcteam.engine.mccore.config.parse.DataSection.getString(String, String)" because "config" is null
[15:15:12] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "mc.promcteam.engine.mccore.config.parse.DataSection.getString(String, String)" because "config" is null
[15:15:12] [Server thread/WARN]: 	at com.sucy.skill.api.skills.Skill.load(Skill.java:852)
[15:15:12] [Server thread/WARN]: 	at com.sucy.skill.dynamic.DynamicSkill.load(DynamicSkill.java:351)
[15:15:12] [Server thread/WARN]: 	at com.sucy.skill.manager.RegistrationManager.lambda$initialize$0(RegistrationManager.java:181)
[15:15:12] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[15:15:12] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[15:15:12] [Server thread/WARN]: 	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
[15:15:12] [Server thread/WARN]: 	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
[15:15:12] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
[15:15:12] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[15:15:12] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[15:15:12] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[15:15:12] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[15:15:12] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:[596](https://aternos.org/log/#L596))
[15:15:12] [Server thread/WARN]: 	at com.sucy.skill.manager.RegistrationManager.initialize(RegistrationManager.java:170)
[15:15:12] [Server thread/WARN]: 	at com.sucy.skill.SkillAPI.onEnable(SkillAPI.java:639)
[15:15:12] [Server thread/WARN]: 	at com.sucy.skill.SkillAPI.reload(SkillAPI.java:534)
[15:15:12] [Server thread/WARN]: 	at com.sucy.skill.cmd.CmdReload.execute(CmdReload.java:53)
[15:15:12] [Server thread/WARN]: 	at mc.promcteam.engine.mccore.commands.ConfigurableCommand.execute(ConfigurableCommand.java:514)
[15:15:12] [Server thread/WARN]: 	at mc.promcteam.engine.mccore.commands.ConfigurableCommand.execute(ConfigurableCommand.java:521)
[15:15:12] [Server thread/WARN]: 	at mc.promcteam.engine.mccore.commands.ConfigurableCommand.execute(ConfigurableCommand.java:484)
[15:15:12] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[15:15:12] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826)
[15:15:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2185)
[15:15:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2000)
[15:15:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1953)
[15:15:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49)
[15:15:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7)
[15:15:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35)
[15:15:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[15:15:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[15:15:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[15:15:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[15:15:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1271)
[15:15:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1264)
[15:15:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[15:15:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1225)
[15:15:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1139)
[15:15:12] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[15:15:12] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[15:15:12] [Server thread/INFO]: [ProSkillAPI] Registration complete
[15:15:12] [Server thread/INFO]: [ProSkillAPI]  - 0 skills
[15:15:12] [Server thread/INFO]: [ProSkillAPI]  - 1 classes

### Environment

```markdown
- Server Software: Paper Spigot 1.16.5
- ProSkillAPI Version: 1.1.76-133024
- ProMCCore Version: 1.0.3.8-1150257
- Plugins: AncientGates, Better Teams, Chest Terminal, CustomEnchanments Deco Heads, DiscordSRV, Essentials, ExoticGardener, ExtraGear, HotbarPets, LaggRemover, LiteXpansion, LuckPerms, Magic, MarriageMaster, Multiverse-Core, Music, MythicMobs, PluginConstructorAPI, ProMCCore, ProMCItems, ProSkillAPI, SkinsRestorer, Slimefun, World Edit
```

### latest.log

 https://mclo.gs/zTGjEbu < the entire logs

**Comment by lordsrubka5** [comment]
Ah this is most likely your skills fault

**Comment by lordsrubka5** [comment]
Your skill file name needs to match up with the names in the first couple lines of that skill config
