### ISSUE TITLE
[Bug]: MMOItems break the combat bar

### ISSUE THREAD

**Issue by RacerN2O** [promcteam/proskillapi#358]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

When having an item created with MMOItems and some of it's attributes (Attack speed, attack damage and some lore for example) in the combat bar, on a subsequent login, the item to swap hotbars will be missing and items in the hotbar will be lost.

Vanilla items seem to work and don't create the error in the log I've given so I assume it's somehow related to item NBT data.

### Expected Behavior

Items should save and load to and from the combat bar as expected.

### Steps To Reproduce

Run server with SkillAPI and MMOItems
Create MMOItem with some different stats and effects
Add item to the combat bar
Leave server, reconnect
Log back in, the item to swap hotbars will be missing until subsquent logins, items in the combat bar will be lost permanently

### Environment

```markdown
- Server Software: purpur-1.18.2-1609
- ProSkillAPI Version: 1.1.7.16-1330244
- ProMCCore Version: 1.0.3.8-1150257
- Plugins: (43): aAnimatedScoreboardf, aAntiDisconnectSpamf, aAuctionHousef, cBeautyQuestsf, aChestCommandsf, aCitizensf, aCutsceneStudiof, aDenizenf, aDiscoFloorf, aDiscordSRVf, aDungeonPartiesf, adynmapf, aEffectLibf, aEssentialsf, aEssentialsChatf, aEssentialsSpawnf, aF3NPermf, aFirstPluginf, aGemsEconomyf, aHeadDBf, aInteractiveBooksf, aLibsDisguisesf, aLuckPermsf, aMCJukeboxf, aMMOItemsf, aModelEnginef, aMP_dev_GUIf, aMPUtilsf, aMultiverse-Coref, aMythicCruciblef, aMythicDungeonsf, aMythicKeysPluginf, aMythicLibf, aMythicMobsf, aPhatLootsf, aPlaceholderAPIf, aProMCCoref, aProSkillAPIf, aProtocolLibf, aShopkeepersf, aVaultf, aWorldEditf, aWorldGuard
```

### latest.log

<details><summary>latest.log</summary>
<p>

```log
[10:42:01] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to ProSkillAPI v1.1.7.16
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at com.sucy.skill.api.util.ItemSerializer.basicDeserialize(ItemSerializer.java:361) ~[proskillapi-1.1.7.16-1330244.jar:?]
	at com.sucy.skill.api.util.ItemSerializer.fromBase64(ItemSerializer.java:215) ~[proskillapi-1.1.7.16-1330244.jar:?]
	at com.sucy.skill.listener.CastCombatListener.init(CastCombatListener.java:92) ~[proskillapi-1.1.7.16-1330244.jar:?]
	at com.sucy.skill.listener.MainListener.lambda$init$0(MainListener.java:121) ~[proskillapi-1.1.7.16-1330244.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at com.sucy.skill.listener.MainListener.init(MainListener.java:121) ~[proskillapi-1.1.7.16-1330244.jar:?]
	at com.sucy.skill.listener.MainListener.onJoin(MainListener.java:169) ~[proskillapi-1.1.7.16-1330244.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor570.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:git-Purpur-1609]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:631) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:363) ~[purpur-1.18.2.jar:git-Purpur-1609]
	at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:305) ~[purpur-1.18.2.jar:git-Purpur-1609]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:320) ~[?:?]
	at net.minecraft.network.Connection.tick(Connection.java:576) ~[?:?]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:201) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1648) ~[purpur-1.18.2.jar:git-Purpur-1609]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:522) ~[purpur-1.18.2.jar:git-Purpur-1609]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1482) ~[purpur-1.18.2.jar:git-Purpur-1609]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[purpur-1.18.2.jar:git-Purpur-1609]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1609]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[10:42:01] [Server thread/INFO]: RacerXXL joined the game
[10:42:01] [Server thread/INFO]: RacerXXL[/156.67.128.243:42045] logged in with entity id 1589 at ([Weltia]-155.43566986792075, 65.0, 62.46942970977295)

```

</p>
</details>

### Anything else?

MMOItems version is v6.7.3/846, in case this information helps.

**Comment by RacerN2O** [comment]
My brother knows programming and has taken a look and says it's due to the flawed item serializer. Perhaps this system should be reworked?

**Comment by Travja** [comment]
Your brother is right! we have actually already fixed this issue in newer dev builds (sorry Spigot isn't updated yet). You can download the latest dev builds through here https://github.com/orgs/promcteam/packages?repo_name=promccore or navigate to them from the dev builds section on Discord.
