### ISSUE TITLE
My ProskillApi will not work! I have restarted everything and rienstalled it all I even made a new server and it still wont work. It won't load my skills or class. Pelase help

### ISSUE THREAD

**Issue by ArcaneFlame520** [promcteam/proskillapi#696]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Steps To Reproduce

I don't know it just happened

### Environment

```markdown
- Server Software:Spigot 1.19.4
- ProSkillAPI Version:latest
- ProMCCore Version:latest
- Plugins:only proskillapi and promccore
```

### latest.log

[13:30:31] [ServerMain/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[13:30:34] [ServerMain/INFO]: Loaded 7 recipes
[13:30:36] [Server thread/INFO]: Starting minecraft server version 1.19.4
[13:30:36] [Server thread/INFO]: Loading properties
[13:30:36] [Server thread/INFO]: This server is running CraftBukkit version 3763-Spigot-7d7b241-5a5e43e (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT)
[13:30:36] [Server thread/INFO]: Debug logging is disabled
[13:30:36] [Server thread/INFO]: Server Ping Player Sample Count: 12
[13:30:36] [Server thread/INFO]: Using 4 threads for Netty based IO
[13:30:36] [Server thread/INFO]: Default game type: SURVIVAL
[13:30:36] [Server thread/INFO]: Generating keypair
[13:30:36] [Server thread/INFO]: Starting Minecraft server on *:25565
[13:30:36] [Server thread/INFO]: Using default channel type
[13:30:37] [Server thread/INFO]: [ProMCCore] Loading 2 libraries... please wait
[13:30:37] [Server thread/INFO]: [ProMCCore] Loaded library D:\Server\libraries\com\mysql\mysql-connector-j\8.2.0\mysql-connector-j-8.2.0.jar
[13:30:37] [Server thread/INFO]: [ProMCCore] Loaded library D:\Server\libraries\com\google\protobuf\protobuf-java\3.21.9\protobuf-java-3.21.9.jar
[13:30:37] [Server thread/INFO]: [ProMCCore] Loaded library D:\Server\libraries\org\apache\commons\commons-lang3\3.12.0\commons-lang3-3.12.0.jar
[13:30:37] [Server thread/INFO]: [ProMCCore] Loading ProMCCore v1.2.0-R0.12-SNAPSHOT
[13:30:37] [Server thread/INFO]: [ProSkillAPI] Loading ProSkillAPI v1.3.0-R0.15-SNAPSHOT
[13:30:38] [Server thread/INFO]: [ProMCCore] Enabling ProMCCore v1.2.0-R0.12-SNAPSHOT
[13:30:38] [Server thread/INFO]: [ProMCCore] You are running MC version V1_19_R3 (RAW: v1_19_R3)
[13:30:38] [Server thread/INFO]: [ProMCCore] Loaded NMS version: V1_19_R3
[13:30:38] [Server thread/INFO]: [ProMCCore] [ItemManager] Successfully registered provider for VANILLA items
[13:30:38] [Server thread/INFO]: [ProMCCore] [ItemManager] Successfully registered provider for ORAXEN items
[13:30:38] [Server thread/INFO]: [ProMCCore] [ItemManager] Successfully registered provider for ITEMSADDER items
[13:30:38] [Server thread/INFO]: [ProMCCore] Found 0 external module(s).
[13:30:38] [Server thread/INFO]: Server version: 11904
[13:30:38] [Server thread/INFO]: [ProMCCore] ProMCCore has been enabled!
[13:30:38] [Server thread/INFO]: [ProMCCore] Plugin loaded in 341 ms!
[13:30:38] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[13:30:38] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[13:30:38] [Server thread/WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[13:30:38] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[13:30:38] [Server thread/INFO]: Preparing level "world"
[13:30:38] [Server thread/INFO]: -------- World Settings For [world] --------
[13:30:38] [Server thread/INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[13:30:38] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[13:30:38] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[13:30:38] [Server thread/INFO]: View Distance: 10
[13:30:38] [Server thread/INFO]: Simulation Distance: 10
[13:30:38] [Server thread/INFO]: Item Merge Radius: 2.5
[13:30:38] [Server thread/INFO]: Item Despawn Rate: 6000
[13:30:38] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[13:30:38] [Server thread/INFO]: Mob Spawn Range: 6
[13:30:38] [Server thread/INFO]: Experience Merge Radius: 3.0
[13:30:38] [Server thread/INFO]: Cactus Growth Modifier: 100%
[13:30:38] [Server thread/INFO]: Cane Growth Modifier: 100%
[13:30:38] [Server thread/INFO]: Melon Growth Modifier: 100%
[13:30:38] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[13:30:38] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[13:30:38] [Server thread/INFO]: Sapling Growth Modifier: 100%
[13:30:38] [Server thread/INFO]: Beetroot Growth Modifier: 100%
[13:30:38] [Server thread/INFO]: Carrot Growth Modifier: 100%
[13:30:38] [Server thread/INFO]: Potato Growth Modifier: 100%
[13:30:38] [Server thread/INFO]: Wheat Growth Modifier: 100%
[13:30:38] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[13:30:38] [Server thread/INFO]: Vine Growth Modifier: 100%
[13:30:38] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[13:30:38] [Server thread/INFO]: Bamboo Growth Modifier: 100%
[13:30:38] [Server thread/INFO]: SweetBerry Growth Modifier: 100%
[13:30:38] [Server thread/INFO]: Kelp Growth Modifier: 100%
[13:30:38] [Server thread/INFO]: TwistingVines Growth Modifier: 100%
[13:30:38] [Server thread/INFO]: WeepingVines Growth Modifier: 100%
[13:30:38] [Server thread/INFO]: CaveVines Growth Modifier: 100%
[13:30:38] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true / Isa false
[13:30:38] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Di 128 / Other 64
[13:30:38] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1 Hopper Can Load Chunks: false
[13:30:38] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Nether: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[13:30:38] [Server thread/INFO]: Max TNT Explosions: 100
[13:30:38] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[13:30:39] [Server thread/INFO]: -------- World Settings For [world_nether] --------
[13:30:39] [Server thread/INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[13:30:39] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[13:30:39] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[13:30:39] [Server thread/INFO]: View Distance: 10
[13:30:39] [Server thread/INFO]: Simulation Distance: 10
[13:30:39] [Server thread/INFO]: Item Merge Radius: 2.5
[13:30:39] [Server thread/INFO]: Item Despawn Rate: 6000
[13:30:39] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[13:30:39] [Server thread/INFO]: Mob Spawn Range: 6
[13:30:39] [Server thread/INFO]: Experience Merge Radius: 3.0
[13:30:39] [Server thread/INFO]: Cactus Growth Modifier: 100%
[13:30:39] [Server thread/INFO]: Cane Growth Modifier: 100%
[13:30:39] [Server thread/INFO]: Melon Growth Modifier: 100%
[13:30:39] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[13:30:39] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[13:30:39] [Server thread/INFO]: Sapling Growth Modifier: 100%
[13:30:39] [Server thread/INFO]: Beetroot Growth Modifier: 100%
[13:30:39] [Server thread/INFO]: Carrot Growth Modifier: 100%
[13:30:39] [Server thread/INFO]: Potato Growth Modifier: 100%
[13:30:39] [Server thread/INFO]: Wheat Growth Modifier: 100%
[13:30:39] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[13:30:39] [Server thread/INFO]: Vine Growth Modifier: 100%
[13:30:39] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[13:30:39] [Server thread/INFO]: Bamboo Growth Modifier: 100%
[13:30:39] [Server thread/INFO]: SweetBerry Growth Modifier: 100%
[13:30:39] [Server thread/INFO]: Kelp Growth Modifier: 100%
[13:30:39] [Server thread/INFO]: TwistingVines Growth Modifier: 100%
[13:30:39] [Server thread/INFO]: WeepingVines Growth Modifier: 100%
[13:30:39] [Server thread/INFO]: CaveVines Growth Modifier: 100%
[13:30:39] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true / Isa false
[13:30:39] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Di 128 / Other 64
[13:30:39] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1 Hopper Can Load Chunks: false
[13:30:39] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Nether: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[13:30:39] [Server thread/INFO]: Max TNT Explosions: 100
[13:30:39] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[13:30:41] [Server thread/INFO]: -------- World Settings For [world_the_end] --------
[13:30:41] [Server thread/INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[13:30:41] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[13:30:41] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[13:30:41] [Server thread/INFO]: View Distance: 10
[13:30:41] [Server thread/INFO]: Simulation Distance: 10
[13:30:41] [Server thread/INFO]: Item Merge Radius: 2.5
[13:30:41] [Server thread/INFO]: Item Despawn Rate: 6000
[13:30:41] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[13:30:41] [Server thread/INFO]: Mob Spawn Range: 6
[13:30:41] [Server thread/INFO]: Experience Merge Radius: 3.0
[13:30:41] [Server thread/INFO]: Cactus Growth Modifier: 100%
[13:30:41] [Server thread/INFO]: Cane Growth Modifier: 100%
[13:30:41] [Server thread/INFO]: Melon Growth Modifier: 100%
[13:30:41] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[13:30:41] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[13:30:41] [Server thread/INFO]: Sapling Growth Modifier: 100%
[13:30:41] [Server thread/INFO]: Beetroot Growth Modifier: 100%
[13:30:41] [Server thread/INFO]: Carrot Growth Modifier: 100%
[13:30:41] [Server thread/INFO]: Potato Growth Modifier: 100%
[13:30:41] [Server thread/INFO]: Wheat Growth Modifier: 100%
[13:30:41] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[13:30:41] [Server thread/INFO]: Vine Growth Modifier: 100%
[13:30:41] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[13:30:41] [Server thread/INFO]: Bamboo Growth Modifier: 100%
[13:30:41] [Server thread/INFO]: SweetBerry Growth Modifier: 100%
[13:30:41] [Server thread/INFO]: Kelp Growth Modifier: 100%
[13:30:41] [Server thread/INFO]: TwistingVines Growth Modifier: 100%
[13:30:41] [Server thread/INFO]: WeepingVines Growth Modifier: 100%
[13:30:41] [Server thread/INFO]: CaveVines Growth Modifier: 100%
[13:30:41] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true / Isa false
[13:30:41] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Di 128 / Other 64
[13:30:41] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1 Hopper Can Load Chunks: false
[13:30:41] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Nether: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[13:30:41] [Server thread/INFO]: Max TNT Explosions: 100
[13:30:41] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[13:30:41] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[13:30:46] [Worker-Main-6/INFO]: Preparing spawn area: 0%
[13:30:46] [Worker-Main-6/INFO]: Preparing spawn area: 0%
[13:30:46] [Worker-Main-6/INFO]: Preparing spawn area: 0%
[13:30:46] [Worker-Main-6/INFO]: Preparing spawn area: 0%
[13:30:46] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[13:30:46] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[13:30:46] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[13:30:46] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[13:30:46] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[13:30:46] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[13:30:46] [Worker-Main-6/INFO]: Preparing spawn area: 0%
[13:30:46] [Worker-Main-3/INFO]: Preparing spawn area: 0%
[13:30:47] [Worker-Main-5/INFO]: Preparing spawn area: 29%
[13:30:47] [Worker-Main-5/INFO]: Preparing spawn area: 89%
[13:30:48] [Server thread/INFO]: Time elapsed: 6589 ms
[13:30:48] [Server thread/INFO]: Preparing start region for dimension minecraft:the_nether
[13:30:50] [Worker-Main-3/INFO]: Preparing spawn area: 0%
[13:30:50] [Worker-Main-4/INFO]: Preparing spawn area: 0%
[13:30:50] [Worker-Main-7/INFO]: Preparing spawn area: 0%
[13:30:50] [Worker-Main-4/INFO]: Preparing spawn area: 0%
[13:30:50] [Worker-Main-6/INFO]: Preparing spawn area: 0%
[13:30:50] [Worker-Main-7/INFO]: Preparing spawn area: 0%
[13:30:51] [Worker-Main-2/INFO]: Preparing spawn area: 24%
[13:30:51] [Worker-Main-5/INFO]: Preparing spawn area: 86%
[13:30:51] [Server thread/INFO]: Time elapsed: 3636 ms
[13:30:51] [Server thread/INFO]: Preparing start region for dimension minecraft:the_end
[13:30:54] [Worker-Main-6/INFO]: Preparing spawn area: 0%
[13:30:54] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[13:30:54] [Worker-Main-5/INFO]: Preparing spawn area: 0%
[13:30:54] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[13:30:54] [Worker-Main-3/INFO]: Preparing spawn area: 0%
[13:30:54] [Worker-Main-3/INFO]: Preparing spawn area: 3%
[13:30:54] [Worker-Main-5/INFO]: Preparing spawn area: 89%
[13:30:54] [Server thread/INFO]: Time elapsed: 3052 ms
[13:30:54] [Server thread/INFO]: [ProSkillAPI] Enabling ProSkillAPI v1.3.0-R0.15-SNAPSHOT
[13:30:55] [Server thread/WARN]: java.lang.StringIndexOutOfBoundsException: Range [4, -1) out of bounds for length 79
[13:30:55] [Server thread/WARN]: 	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
[13:30:55] [Server thread/WARN]: 	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
[13:30:55] [Server thread/WARN]: 	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
[13:30:55] [Server thread/WARN]: 	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
[13:30:55] [Server thread/WARN]: 	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
[13:30:55] [Server thread/WARN]: 	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112)
[13:30:55] [Server thread/WARN]: 	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349)
[13:30:55] [Server thread/WARN]: 	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4608)
[13:30:55] [Server thread/WARN]: 	at java.base/java.lang.String.substring(String.java:2720)
[13:30:55] [Server thread/WARN]: 	at mc.promcteam.engine.mccore.config.parse.YAMLParser.parse(YAMLParser.java:169)
[13:30:55] [Server thread/WARN]: 	at mc.promcteam.engine.mccore.config.parse.YAMLParser.parse(YAMLParser.java:228)
[13:30:55] [Server thread/WARN]: 	at mc.promcteam.engine.mccore.config.parse.YAMLParser.parse(YAMLParser.java:228)
[13:30:55] [Server thread/WARN]: 	at mc.promcteam.engine.mccore.config.parse.YAMLParser.parseText(YAMLParser.java:133)
[13:30:55] [Server thread/WARN]: 	at mc.promcteam.engine.mccore.config.parse.YAMLParser.parseText(YAMLParser.java:117)
[13:30:55] [Server thread/WARN]: 	at mc.promcteam.engine.mccore.config.parse.YAMLParser.parseFile(YAMLParser.java:100)
[13:30:55] [Server thread/WARN]: 	at mc.promcteam.engine.mccore.config.CommentedConfig.reload(CommentedConfig.java:100)
[13:30:55] [Server thread/WARN]: 	at mc.promcteam.engine.mccore.config.CommentedConfig.getConfig(CommentedConfig.java:108)
[13:30:55] [Server thread/WARN]: 	at com.sucy.skill.manager.RegistrationManager.initialize(RegistrationManager.java:224)
[13:30:55] [Server thread/WARN]: 	at com.sucy.skill.SkillAPI.onEnable(SkillAPI.java:668)
[13:30:55] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266)
[13:30:55] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[13:30:55] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[13:30:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:541)
[13:30:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:455)
[13:30:55] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:589)
[13:30:55] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414)
[13:30:55] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250)
[13:30:55] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:975)
[13:30:55] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
[13:30:55] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1623)
[13:30:55] [Server thread/WARN]: java.lang.StringIndexOutOfBoundsException: Range [4, -1) out of bounds for length 79
[13:30:55] [Server thread/WARN]: 	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
[13:30:55] [Server thread/WARN]: 	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
[13:30:55] [Server thread/WARN]: 	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
[13:30:55] [Server thread/WARN]: 	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
[13:30:55] [Server thread/WARN]: 	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
[13:30:55] [Server thread/WARN]: 	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112)
[13:30:55] [Server thread/WARN]: 	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349)
[13:30:55] [Server thread/WARN]: 	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4608)
[13:30:55] [Server thread/WARN]: 	at java.base/java.lang.String.substring(String.java:2720)
[13:30:55] [Server thread/WARN]: 	at mc.promcteam.engine.mccore.config.parse.YAMLParser.parse(YAMLParser.java:169)
[13:30:55] [Server thread/WARN]: 	at mc.promcteam.engine.mccore.config.parse.YAMLParser.parse(YAMLParser.java:228)
[13:30:55] [Server thread/WARN]: 	at mc.promcteam.engine.mccore.config.parse.YAMLParser.parse(YAMLParser.java:228)
[13:30:55] [Server thread/WARN]: 	at mc.promcteam.engine.mccore.config.parse.YAMLParser.parseText(YAMLParser.java:133)
[13:30:55] [Server thread/WARN]: 	at mc.promcteam.engine.mccore.config.parse.YAMLParser.parseText(YAMLParser.java:117)
[13:30:55] [Server thread/WARN]: 	at mc.promcteam.engine.mccore.config.parse.YAMLParser.parseFile(YAMLParser.java:100)
[13:30:55] [Server thread/WARN]: 	at mc.promcteam.engine.mccore.config.CommentedConfig.reload(CommentedConfig.java:100)
[13:30:55] [Server thread/WARN]: 	at mc.promcteam.engine.mccore.config.CommentedConfig.getConfig(CommentedConfig.java:108)
[13:30:55] [Server thread/WARN]: 	at com.sucy.skill.manager.RegistrationManager.getBaseSection(RegistrationManager.java:327)
[13:30:55] [Server thread/WARN]: 	at com.sucy.skill.manager.RegistrationManager.lambda$initialize$1(RegistrationManager.java:267)
[13:30:55] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[13:30:55] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[13:30:55] [Server thread/WARN]: 	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
[13:30:55] [Server thread/WARN]: 	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1921)
[13:30:55] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[13:30:55] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[13:30:55] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[13:30:55] [Server thread/WARN]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[13:30:55] [Server thread/WARN]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[13:30:55] [Server thread/WARN]: 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[13:30:55] [Server thread/WARN]: 	at com.sucy.skill.manager.RegistrationManager.initialize(RegistrationManager.java:260)
[13:30:55] [Server thread/WARN]: 	at com.sucy.skill.SkillAPI.onEnable(SkillAPI.java:668)
[13:30:55] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266)
[13:30:55] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[13:30:55] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[13:30:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:541)
[13:30:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:455)
[13:30:55] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:589)
[13:30:55] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414)
[13:30:55] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250)
[13:30:55] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:975)
[13:30:55] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
[13:30:55] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1623)
[13:30:55] [Server thread/ERROR]: [ProSkillAPI] Failed to load class file: Spellthief - Spellthief.yml does not appear to contain any class data
[13:30:55] [Server thread/INFO]: [ProSkillAPI] Registration complete
[13:30:55] [Server thread/INFO]: [ProSkillAPI]  - 0 skills
[13:30:55] [Server thread/INFO]: [ProSkillAPI]  - 0 classes
[13:30:55] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[13:30:55] [Server thread/INFO]: Done (17.080s)! For help, type "help"
[13:40:24] [User Authenticator #1/INFO]: [ProSkillAPI] Created a new folder for config files
[13:40:24] [User Authenticator #1/INFO]: UUID of player Eragon is ad563e73-6157-3c8d-9463-16de2df17c0e
[13:40:24] [Server thread/INFO]: Eragon joined the game
[13:40:24] [Server thread/INFO]: Eragon[/127.0.0.1:50558] logged in with entity id 61 at ([world]8.5, 64.0, 24.5)
[13:40:41] [Server thread/INFO]: Eragon issued server command: /class profess
[13:40:45] [Server thread/INFO]: Eragon issued server command: /class customize
[13:40:48] [Server thread/INFO]: Eragon lost connection: Disconnected
[13:40:48] [Server thread/INFO]: Eragon left the game
[13:41:48] [Server thread/INFO]: Plugins (2): [0;32;1mProMCCore[0;37;1m, [0;32;1mProSkillAPI (SkillAPI)[m
[13:42:03] [Server thread/INFO]: Unknown command. Type "/help" for help.[m
[13:42:07] [Server thread/INFO]: This server is running CraftBukkit version 3763-Spigot-7d7b241-5a5e43e (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT)[m
[13:42:07] [Server thread/INFO]: You are 52 version(s) behind[m
[13:42:30] [Server thread/INFO]: Plugins (2): [0;32;1mProMCCore[0;37;1m, [0;32;1mProSkillAPI (SkillAPI)[m
[13:43:06] [Server thread/INFO]: Stopping the server
[13:43:06] [Server thread/INFO]: Stopping server
[13:43:06] [Server thread/INFO]: [ProSkillAPI] Disabling ProSkillAPI v1.3.0-R0.15-SNAPSHOT
[13:43:06] [Server thread/INFO]: [ProMCCore] Disabling ProMCCore v1.2.0-R0.12-SNAPSHOT
[13:43:06] [Server thread/INFO]: Saving players
[13:43:06] [Server thread/INFO]: Saving worlds
[13:43:09] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[13:43:14] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world_nether]'/minecraft:the_nether
[13:43:23] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world_the_end]'/minecraft:the_end
[13:43:23] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[13:43:23] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[13:43:23] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[13:43:23] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved

**Comment by Travja** [comment]
Yeah, unfortunately I pushed some stuff to the editor over the weekend that broke yaml a bit for how the plugins parse it. There are new builds on our Discord of Core and PSAPI that should resolve things for you

**Comment by ArcaneFlame520** [comment]
I can't do discord sorry

**Comment by ArcaneFlame520** [comment]
Could you send me them another way?

**Comment by ArcaneFlame520** [comment]
Let me try that.

**Comment by ArcaneFlame520** [comment]
Ok I think that worked. Also GREAT plugin really easy to use and sooooo well built. You can just start making them immediately with the online editor!

**Comment by ArcaneFlame520** [comment]
Yep class loaded

**Comment by Travja** [comment]
PSAPI: https://s01.oss.sonatype.org/content/repositories/snapshots/com/promcteam/proskillapi/1.3.0-R0.20-SNAPSHOT/proskillapi-1.3.0-R0.20-20240227.052819-1.jar

CORE: https://s01.oss.sonatype.org/service/local/repositories/releases/content/com/promcteam/promccore/1.2.0-R2/promccore-1.2.0-R2.jar

**Comment by ArcaneFlame520** [comment]
Thanks
